# Generated by Django 3.0.2 on 2020-01-29 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colorme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='商品ID'),
        ),
        migrations.AlterField(
            model_name='uploadfileerrorrecord',
            name='parent_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='colorme.UploadFile', verbose_name='親ファイル'),
        ),
    ]
