# Generated by Django 3.0.2 on 2020-01-31 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colorme', '0002_auto_20200130_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='record_count',
        ),
        migrations.AlterField(
            model_name='item',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colorme_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='option',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='colorme.Item'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='csv_file',
            field=models.FileField(upload_to='uploaded', verbose_name='product.csv'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
