# Generated by Django 3.0.2 on 2020-02-01 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colorme', '0003_auto_20200131_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='kataban',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='option_2_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
