# Generated by Django 3.0.2 on 2020-02-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colorme', '0005_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
