# Generated by Django 3.0.2 on 2020-01-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oauth',
            fields=[
                ('client_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('client_secret_id', models.CharField(max_length=100)),
                ('redirect_uri', models.CharField(max_length=100)),
                ('authorization_code', models.CharField(blank=True, max_length=100, null=True)),
                ('access_token', models.CharField(blank=True, max_length=100, null=True)),
                ('access_token_expires_in', models.DateTimeField(blank=True, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
