# Generated by Django 3.0.2 on 2020-02-09 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('detail', models.TextField()),
                ('price', models.IntegerField()),
                ('proper_price', models.IntegerField(blank=True, null=True)),
                ('item_tax_type', models.IntegerField()),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('visible', models.IntegerField()),
                ('list_order', models.IntegerField()),
                ('identifier', models.CharField(max_length=100, null=True)),
                ('img1_origin', models.URLField(blank=True, max_length=255, null=True)),
                ('img2_origin', models.URLField(blank=True, max_length=255, null=True)),
                ('img3_origin', models.URLField(blank=True, max_length=255, null=True)),
                ('img4_origin', models.URLField(blank=True, max_length=255, null=True)),
                ('img5_origin', models.URLField(blank=True, max_length=255, null=True)),
                ('img6_origin', models.URLField(blank=True, max_length=255, null=True)),
                ('img7_origin', models.URLField(blank=True, max_length=255, null=True)),
                ('img8_origin', models.URLField(blank=True, max_length=255, null=True)),
                ('img9_origin', models.URLField(blank=True, max_length=255, null=True)),
                ('img10_origin', models.URLField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Oauth',
            fields=[
                ('client_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('client_secret_id', models.CharField(max_length=100)),
                ('redirect_uri', models.CharField(max_length=100)),
                ('authorization_code', models.CharField(blank=True, max_length=100, null=True)),
                ('access_token', models.CharField(blank=True, max_length=100, null=True)),
                ('access_token_expires_in', models.DateTimeField(blank=True, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_id', models.IntegerField(blank=True, null=True)),
                ('variation', models.CharField(max_length=100)),
                ('variation_stock', models.IntegerField()),
                ('variation_identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='thebase.Item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_category_id', models.IntegerField(unique=True)),
                ('item_id', models.IntegerField()),
                ('category_id', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('list_order', models.IntegerField()),
                ('number', models.IntegerField()),
                ('parent_number', models.IntegerField(default=0)),
                ('code', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
