# Generated by Django 3.0.2 on 2020-01-30 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thebase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('category_id', models.CharField(blank=True, max_length=255, null=True)),
                ('detail', models.TextField()),
                ('price', models.IntegerField()),
                ('proper_price', models.IntegerField()),
                ('item_tax_type', models.IntegerField()),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('visible', models.IntegerField()),
                ('list_order', models.IntegerField()),
                ('identifier', models.CharField(max_length=100, null=True)),
                ('image_1_origin', models.URLField(blank=True, max_length=255, null=True)),
                ('image_2_origin', models.URLField(blank=True, max_length=255, null=True)),
                ('image_3_origin', models.URLField(blank=True, max_length=255, null=True)),
                ('image_4_origin', models.URLField(blank=True, max_length=255, null=True)),
                ('image_5_origin', models.URLField(blank=True, max_length=255, null=True)),
                ('image_6_origin', models.URLField(blank=True, max_length=255, null=True)),
                ('image_7_origin', models.URLField(blank=True, max_length=255, null=True)),
                ('image_8_origin', models.URLField(blank=True, max_length=255, null=True)),
                ('image_9_origin', models.URLField(blank=True, max_length=255, null=True)),
                ('image_10_origin', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('identifier', models.CharField(max_length=100)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='thebase.Item')),
            ],
        ),
    ]
