# Generated by Django 3.0.2 on 2020-01-30 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thebase', '0003_item_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='image_10_origin',
            new_name='img10_origin',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='image_1_origin',
            new_name='img1_origin',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='image_2_origin',
            new_name='img2_origin',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='image_3_origin',
            new_name='img3_origin',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='image_4_origin',
            new_name='img4_origin',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='image_5_origin',
            new_name='img5_origin',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='image_6_origin',
            new_name='img6_origin',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='image_7_origin',
            new_name='img7_origin',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='image_8_origin',
            new_name='img8_origin',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='image_9_origin',
            new_name='img9_origin',
        ),
    ]
