# Generated by Django 3.0.2 on 2020-01-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thebase', '0004_auto_20200130_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='identifier',
            new_name='variation_id',
        ),
        migrations.RenameField(
            model_name='variation',
            old_name='stock',
            new_name='variation_stock',
        ),
        migrations.AddField(
            model_name='variation',
            name='variation_identifier',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
