# Generated by Django 3.0.2 on 2020-01-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thebase', '0005_auto_20200130_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
