# Generated by Django 3.0.2 on 2020-01-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thebase', '0006_auto_20200130_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='proper_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
