# Generated by Django 3.0.2 on 2020-01-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thebase', '0007_auto_20200130_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_identifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
