# Generated by Django 3.0.2 on 2020-02-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thebase', '0009_category_itemcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.IntegerField(unique=True),
        ),
    ]
