# Generated by Django 3.0.2 on 2020-02-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thebase', '0010_auto_20200202_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.AddField(
            model_name='category',
            name='parent_number',
            field=models.IntegerField(default=0),
        ),
    ]
