# Generated by Django 3.0.2 on 2020-02-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thebase', '0011_auto_20200202_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='itemcategory',
            name='item',
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='category_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='item_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
