# Generated by Django 3.0.2 on 2020-01-18 14:20

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thebase', '0001_initial'),
        ('wowma', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='thebase_auth',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='thebase.Oauth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wowma_auth',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='wowma.AuthInfo'),
        ),
    ]
