FILE_TYPE_PRODUCT = '0'
FILE_TYPE_OPTION = '1'

PRODUCT_COLUMNS = [
    'item_id',
    'category_1',
    'category_2',
    'kataban',
    'item_name',
    'image_url',
    'create_feature_phone_image',
    'extra_image_1_url',
    'extra_image_2_url',
    'extra_image_3_url',
    'extra_image_4_url',
    'extra_image_5_url',
    'extra_image_6_url',
    'extra_image_7_url',
    'extra_image_8_url',
    'extra_image_9_url',
    'sell_price',
    'member_price',
    'regular_price',
    'cost_price',
    'stock_count',
    'manage_stock',
    'min_purchase_qty',
    'max_purchase_qty',
    'sale_start_date',
    'sale_start_time',
    'sale_end_date',
    'sale_end_time',
    'unit',
    'weight',
    'outstock_message',
    'optimal_stock_count',
    'display_seq',
    'short_description',
    'description',
    'description_for_feature_phone_shop',
    'description_for_smartphone_shop',
    'trackback_acceptance',
    'use_new_mark',
    'new_mark_image',
    'ad_category_id',
    'ad_tag_1',
    'ad_tag_2',
    'ad_tag_3',
    'ad_description',
    'brand',
    'jan_isbn',
    'mpn',
    'condition',
    'gender',
    'color',
    'size',
    'title',
    'keyword',
    'page_abstract',
    'transfer_fee',
    'display_status',
    'discount_tax_rate'
]
OPTION_COLUMNS = [
    'item_id',
    'name_or_value',
    'option_1_value',
    'option_2_value',
    'option_id',
    'kataban',
    'stock_count',
    'optimal_stock_count',
    'sale_price',
    'member_price',
]

JOB_STATUS_WAITING = '1'
JOB_STATUS_IN_PROGRESS = '2'
JOB_STATUS_COMPLETED = '3'
JOB_STATUS_MESSAGES = {
    JOB_STATUS_WAITING: '待機中',
    JOB_STATUS_IN_PROGRESS: '実行中',
    JOB_STATUS_COMPLETED: '完了'
}