WOWMA_ENDPOINT = 'https://api.manager.wowma.jp/wmshopapi/'

API_MODE_REGISTER = 'register'
API_MODE_UPDATE = 'update'
API_MDOE_DELETE = 'delete'

API_STATUS_SUCCESS = '0'
API_STATUS_ERROR = '1'

ITEMS_PER_PAGE = 10

SELL_METHODS = {
    '1': '通常販売',
    '2': '予約販売'
}
SALE_STATUS_ONSALE = '1'
SALE_STATUS_OFFSALE = '2'
SALE_STATUS = {
    SALE_STATUS_ONSALE: '販売中',
    SALE_STATUS_OFFSALE: '販売停止中'
}

TIMING_VALIDATION = 'validation'
TIMING_RUNTIME = 'runtime'

CSV_TYPE_ITEM = 'item'
CSV_TYPE_STOCK = 'stock'


STOCK_SEGMENT_NO_CHOICE = '1'
STOCK_SEGMENT_CHOICES = '2'
DISPLAY_STOCK_SEGMENT_NO = '1'
DISPLAY_STOCK_SEGMENT_YES = '2'
DISPLAY_STOCK_SEGMENT_OCCASOINAL = '3'

class ItemCols:
    COLUMN_COUNT = 209

    CTRL_COL = 0
    LOT_NUMBER = 1
    ITEM_NAME = 2
    ITEM_MANAGEMENT_ID = 3
    ITEM_MANAGEMENT_NAME = 4
    ITEM_CODE = 5
    ITEM_PRICE = 6
    SELL_METHOD_SEGMENT = 7
    RELEASE_DATE = 8
    MAKER_RETAIL_PRICE = 9
    MAKER_RETAIL_PRICE_URL = 10
    TAX_SEGMENT = 11
    REDUCED_TAX = 12
    POSTAGE_SEGMENT = 13
    POSTAGE = 14
    DELIVERY_ID = 15
    DELIVERY_METHOD_ID_START = 16
    DELIVERY_METHOD_NAME_START = 21
    SELL_START_DATE = 26
    SELL_END_DATE = 27
    COUNTDOWN_TIMER_CONFIG = 28
    SELL_NUMBER_DISP_CONFIG = 29
    BUY_NUM_LIMIT_CONFIG = 30
    BUY_NUM_MAX = 31
    PUBLIC_START_DATE = 32
    GIFT_PACKING_SEGMENT = 33
    NOSHI_SEGMENT = 34
    LIMITED_ORDER_SEGMENT = 35
    LIMITED_ORDER_COUNT = 36
    DESCRIPTION = 37
    DESCRIPTION_FORSP = 38
    DESCRIPTION_FORPC = 39
    DETAIL_TITLE = 40
    DETAIL_DESCRIPTION = 41
    SPEC_TITLE = 42
    SPEC_START = 43
    SEARCH_KEYWORD_START = 48
    SEARCH_TARGET = 51
    IMAGE_NAME_START = 52
    IMAGE_URL_START = 72
    CATEGORY_ID = 92
    TAG_ID = 93
    SHOP_CATEGORY_ID_START = 94
    SHOP_CATEGORY_DISP_SEQ = 104
    JAN = 105
    ISBN = 106
    ITEM_MODEL = 107
    LIMITED_PASSWD = 108
    LIMITED_PASSWD_PAGE_TITLE = 109
    LIMITED_PASSWD_PAGE_MESSAGE = 110
    SALE_STATUS = 111
    CROSS_BORDER_EC_LNK_CONFIG = 112
    ITEM_OPTION_START = 113
    ITEM_OPTION_COMMISSION_START = 123
    POINT_RATE = 193
    STOCK_REQUEST_CONFIG = 194
    RETURN_REQUEST_CONFIG = 195
    DELIVERY_LEADTIME_ID = 196
    STOCK_SEGMENT = 197
    DISPLAY_BACKORDER_MESSAGE = 198
    STOCK_COUNT = 199
    STOCK_SHIPPING_DAY_ID = 200
    DISPLAY_STOCK_SEGMENT = 201
    DISPLAY_STOCK_THRESHOLD = 202
    CHOICES_STOCK_HORIZONTAL_ITEM_NAME = 203
    CHOICES_STOCK_VERTICAL_ITEM_NAME = 204
    CHOICES_STOCK_UPPER_DESCRIPTION = 205
    CHOICES_STOCK_LOWER_DESCRIPTION = 206
    DISPLAY_CHOICES_STOCK_SEGMENT = 207
    DISPLAY_CHOICES_STOCK_THRESHOLD = 208

class StockCols:
    COLUMN_COUNT = 14
    
    CTRL_COL = 0
    ITEM_CODE = 1
    STOCK_SEGMENT = 2
    STOCK_COUNT = 3
    CHOICES_STOCK_HORIZONTAL_NAME = 4
    CHIOCES_STOCK_HORIZONTAL_CODE = 5
    CHOICES_STOCK_HORIZONTAL_SEQ = 6
    CHOICES_STOCK_VERTICAL_NAME = 7
    CHIOCES_STOCK_VERTICAL_CODE = 8
    CHOICES_STOCK_VERTICAL_SEQ = 9
    CHOICES_STOCK_COUNT = 10
    CHOICES_STOCK_SHIPPING_DAY_ID = 11
    CHOICES_STOCK_IMAGE_URL = 12
    CHOICES_STOCK_COLOR_SEGMENT = 13

