# Generated by Django 3.0.2 on 2020-01-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthInfo',
            fields=[
                ('application_key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('store_id', models.CharField(max_length=10)),
            ],
        ),
    ]
