# Generated by Django 3.0.2 on 2020-02-09 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthInfo',
            fields=[
                ('application_key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('store_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SerializableModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('serializablemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wowma.SerializableModel')),
                ('ctgryId', models.IntegerField()),
                ('ctgryNameFullpath', models.CharField(max_length=255)),
            ],
            bases=('wowma.serializablemodel',),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('serializablemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wowma.SerializableModel')),
                ('lotNumber', models.IntegerField(null=True, unique=True)),
                ('itemName', models.CharField(max_length=128)),
                ('itemManagementId', models.CharField(blank=True, max_length=128, null=True)),
                ('itemManagementName', models.CharField(blank=True, max_length=128, null=True)),
                ('itemCode', models.CharField(blank=True, max_length=128, null=True)),
                ('itemPrice', models.IntegerField()),
                ('sellMethodSegment', models.CharField(default='1', max_length=1)),
                ('taxSegment', models.CharField(default='1', max_length=1)),
                ('postageSegment', models.CharField(default='2', max_length=1)),
                ('description', models.TextField()),
                ('descriptionForSP', models.TextField()),
                ('descriptionForPC', models.TextField()),
                ('categoryId', models.CharField(blank=True, max_length=20, null=True)),
                ('saleStatus', models.CharField(default='1', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wowma_items', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('wowma.serializablemodel',),
        ),
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
                ('serializablemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wowma.SerializableModel')),
                ('shopCategoryId', models.IntegerField(unique=True)),
                ('shopCategoryLevel', models.CharField(max_length=1)),
                ('shopCategoryName', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wowma_categories', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('wowma.serializablemodel',),
        ),
        migrations.CreateModel(
            name='RegisterStock',
            fields=[
                ('serializablemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wowma.SerializableModel')),
                ('stockSegment', models.CharField(max_length=1)),
                ('stockCount', models.CharField(blank=True, max_length=5, null=True)),
                ('choicesStockHorizontalItemName', models.CharField(max_length=50)),
                ('choicesStockVerticalItemName', models.CharField(max_length=50)),
                ('parent_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wowma.Item')),
            ],
            bases=('wowma.serializablemodel',),
        ),
        migrations.CreateModel(
            name='ItemShopCategory',
            fields=[
                ('serializablemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wowma.SerializableModel')),
                ('parent_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopCategories', to='wowma.Item')),
                ('shopCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wowma.ShopCategory')),
            ],
            bases=('wowma.serializablemodel',),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('serializablemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wowma.SerializableModel')),
                ('imageUrl', models.URLField(max_length=255)),
                ('imageName', models.CharField(max_length=16)),
                ('imageSeq', models.CharField(max_length=2)),
                ('parent_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='wowma.Item')),
            ],
            bases=('wowma.serializablemodel',),
        ),
        migrations.CreateModel(
            name='ChoicesStockVertical',
            fields=[
                ('serializablemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wowma.SerializableModel')),
                ('choicesStockVerticalCode', models.CharField(max_length=255)),
                ('choicesStockVerticalName', models.CharField(max_length=100)),
                ('choicesStockVerticalSeq', models.CharField(max_length=2)),
                ('registerStock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verticals', to='wowma.RegisterStock')),
            ],
            bases=('wowma.serializablemodel',),
        ),
        migrations.CreateModel(
            name='ChoicesStockHorizontal',
            fields=[
                ('serializablemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wowma.SerializableModel')),
                ('choicesStockHorizontalCode', models.CharField(max_length=255)),
                ('choicesStockHorizontalName', models.CharField(max_length=100)),
                ('choicesStockHorizontalSeq', models.CharField(max_length=2)),
                ('registerStock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horizontals', to='wowma.RegisterStock')),
            ],
            bases=('wowma.serializablemodel',),
        ),
        migrations.CreateModel(
            name='ChoicesStock',
            fields=[
                ('serializablemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wowma.SerializableModel')),
                ('choicesStockVerticalCode', models.CharField(max_length=255)),
                ('choicesStockHorizontalCode', models.CharField(max_length=255)),
                ('choicesStockCount', models.CharField(max_length=5)),
                ('registerStock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choicesStocks', to='wowma.RegisterStock')),
            ],
            bases=('wowma.serializablemodel',),
        ),
    ]
