# Generated by Django 2.1.5 on 2020-01-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowma', '0002_uploadedfile_uploadfileerrorrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfileerrorrecord',
            name='timing',
            field=models.CharField(default=1, max_length=100, verbose_name='エラータイミング'),
            preserve_default=False,
        ),
    ]
